name: Docker Lint

on:
  workflow_call:
    inputs:
      ignore:
        required: false
        type: string
      file:
        required: true
        type: string

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Docker files
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.file }}
          recursive: true
          verbose: true
          ignore: ${{ inputs.ignore }}
