name: Docker Lint

on:
  workflow_call:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Docker files
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          recursive: true
          verbose: true
          ignore: "DL3008,DL3025"
